<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>icon\icon.ico</ApplicationIcon>
        <Authors>PureLogicCode</Authors>
        <Company>PureLogicCode.com</Company>
        <IsPackable>false</IsPackable>
        <AssemblyVersion>2.7.2</AssemblyVersion>
        <FileVersion>2.7.2</FileVersion>
        <NeutralLanguage>en</NeutralLanguage>
        <DebugType>embedded</DebugType>
        <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="icon\icon.ico" />
        <None Include="bchunk.exe">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="extract-xiso.exe">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="xdvdfs.exe">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="7za.exe">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="7za_arm64.exe">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Meziantou.Analyzer" Version="3.0.203">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
        <PackageReference Include="Roslynator.Analyzers" Version="5.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="5.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.Formatting.Analyzers" Version="5.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="SharpCompress" Version="0.50.4" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="References\**" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="References\**" />
    </ItemGroup>

    <ItemGroup>
        <Page Remove="References\**" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="images\about.png" />
        <Resource Include="images\about.png" />
        <None Remove="images\exit.png" />
        <Resource Include="images\exit.png" />
        <None Remove="images\logo.png" />
        <Resource Include="images\logo.png" />
    </ItemGroup>

</Project>